//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment_05Opt_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public long IdCourse { get; set; }
        public string NameCourse { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Feedbacktype { get; set; }
    }
}
